### ISSUE TITLE
OpenCV error.  Version : 2.4.11

### ISSUE THREAD

**Issue by KathiravanNatarajan** [VasuAgrawal/GestureDetection#2]
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /home/travis/miniconda/conda-bld/work/opencv-2.4.11/modules/imgproc/src/color.cpp, line 3739
Traceback (most recent call last):
  File "testImplementation.py", line 206, in <module>
    GestureDemo().run()
  File "testImplementation.py", line 200, in run
    super(GestureDemo, self).run()
  File "/home/kathirdrone/Desktop/ARDRONE /GestureDetection/GestureDetection/current_src/eventBasedAnimationClass.py", line 47, in run
    self.onTimerFiredWrapper()
  File "/home/kathirdrone/Desktop/ARDRONE /GestureDetection/GestureDetection/current_src/eventBasedAnimationClass.py", line 30, in onTimerFiredWrapper
    self.onTimerFired()
  File "testImplementation.py", line 125, in onTimerFired
    self.gp.process()
  File "/home/kathirdrone/Desktop/ARDRONE /GestureDetection/GestureDetection/current_src/GesturesApi.py", line 297, in process
    self.threshold()
  File "/home/kathirdrone/Desktop/ARDRONE /GestureDetection/GestureDetection/current_src/GesturesApi.py", line 111, in threshold
    grey = cv2.cvtColor(self.original, cv2.COLOR_BGR2GRAY)
cv2.error: /home/travis/miniconda/conda-bld/work/opencv-2.4.11/modules/imgproc/src/color.cpp:3739: error: (-215) scn == 3 || scn == 4 in function cvtColor

**Comment by VasuAgrawal** [comment]
Can you give me some more information on your setup, in order for me to try to replicate this error?

**Comment by KathiravanNatarajan** [comment]
Yeah. I found the error, Since I was using virtualBox I couldn't connect my webcam with the guest OS. Thanks for the reply.
